org: adamstudentorg
service: swingnotes-api-codereview

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1  

functions:
  getNotes:
    handler: functions/getNotes.handler
    events:
      - httpApi:
          path: /api/notes/{username}
          method: GET

  addNote:
    handler: functions/addNote.handler
    events:
      - httpApi:
          path: /api/notes/{username}
          method: POST

  updateNote:
    handler: functions/updateNote.handler
    events:
      - httpApi:
          path: /api/notes/{id}
          method: PUT

  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - httpApi:
          path: /api/notes/{id}
          method: DELETE
